# Generated by Django 5.1.3 on 2025-01-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
                ('account_number', models.IntegerField()),
                ('opening_balance', models.IntegerField()),
                ('activity', models.IntegerField()),
                ('closing_balance', models.IntegerField(editable=False)),
            ],
        ),
    ]
